### ISSUE TITLE
Sidebar overlaps footer

### ISSUE THREAD

**Issue by sorcamarian** [StackExchange/stackexchange.github.com#5]
On the post edit page, the sidebar(recommandations) overlaps the footer.

![image](https://cloud.githubusercontent.com/assets/12509753/17830571/fd806690-66d7-11e6-8aca-1ac053b653e3.png)

**Comment by bretcope** [comment]
Issues with Stack Exchange sites should be brought up on https://meta.stackexchange.com or on a specific child meta, such as https://meta.stackoverflow.com. The `bug` and `design` tags would be appropriate for this particular issue.

This github repo is simply for the webpage which displays links to our open source projects.
